on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.1
      - name: Setup python
        uses: actions/setup-python@v5.0.0
        with:
          python-version: 3.12
      - name: Setup rye
        uses: eifinger/setup-rye@v3
        with:
          version: "latest"
      - name: Sync project dependencies
        run: rye sync
  publish:
    name: Publish package
    environment: release
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    needs: [build]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.1
      - name: Setup python
        uses: actions/setup-python@v5.0.0
        with:
          python-version: 3.12
      - name: Setup rye
        uses: eifinger/setup-rye@v3
        with:
          version: "latest"
      - name: Package project
        run: rye build --wheel -o dist -c
      - name: Publish to pypi
        uses: pypa/gh-action-pypi-publish@release/v1
